### ISSUE TITLE
Program algorithm

### ISSUE THREAD

**Issue by ZahraHosseini-04** [sadafnazari97/Persian_handwriting_recognition#11]
Hello
Has a classifier been used in this project?
If you use it, thank you for explanation of what algorithm you used to train the classifier model.
How you implemented this algorithm in your project?

**Comment by sadafnazari** [comment]
Hello,
A Convolutional Neural Network has been used for classification. 
The model definition can be found  in `src/utils/model.py`. It will be trained in `src/train_models.py` and the inference will take place in `src/prediction.py`.
I would be glad to help if you ask your questions with more details! 

Br,
Sadaf Nazari

**Comment by ZahraHosseini-04** [comment]
Hello,
Thank you for your guidance
