### ISSUE TITLE
Request the requirements.txt file

### ISSUE THREAD

**Issue by HadisRafati** [sadafnazari97/Persian_handwriting_recognition#5]
Hello
I get an error to run the project and I think I need the requirements.txt file
Thank you for adding it to the project file.

**Comment by sadafnazari** [comment]
Hello,

Thank you for reporting this issue.

The requirements are now added to the project. 

If this does not solve the error, please paste the error message so that I can provide better help.

Br,
Sadaf Nazari

**Comment by HadisRafati** [comment]
Thank you for your reply

I encountered this error while installing the packages
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'E:\\Persian_handwriting_recognition-master-edit-requ\\Persian_handwriting_recognition-master\\venv\\Lib\\site-packages\ \tensorflow\\include\\external\\llvm-project\\mlir\\_virtual_includes\\AffineMemoryOpInterfacesIncGen\\mlir\\Dialect\\Affine\\IR\\AffineMemoryOpInterfaces.cpp.inc'
HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths

Thank you for your guidance.

**Comment by HadisRafati** [comment]
Thank you very much for your reply and guidance.
